### ISSUE TITLE
Please list Qt requirements

### ISSUE THREAD

**Issue by yurivict** [wwmm/wwplot#1]
The README lists gtk dependencies, but on my system it prints:

```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
```
which means that it runs through Qt.

Please:
1. In the README, list Qt dependencies that are requires
2. Explain how to switch it to Qt or Gtk when both are available.

For example, when the ```wwplot``` package is installed, Qt is set as a dependency. There should be a way to tell it that only Qt should be used, otherwise it would just switch to Gtk when it would be installed, which would be strange.

**Comment by wwmm** [comment]
I totally forgot about updating the readme. Sorry! I moved from GTK to QT. So it is not going to switch from one to another. It is only QT now.

As far as I could see the QT dependencies on Arch Linux are `Pyside2`, `qt5-base` and `qt5-declarative`.

I will update the readme.

**Comment by yurivict** [comment]
But it apparently uses QtWebEngine too, based on the warning above.
How to eliminate this warning?

**Comment by wwmm** [comment]
I do not use the web engine(at least not directly). No idea why you are seeing this warning. These are the Qt packages I have installed in Arch Linux
```
local/qt5-base 5.13.0-7 (qt qt5)
    A cross-platform application and UI framework
local/qt5-declarative 5.13.0-1 (qt qt5)
    Classes for QML and JavaScript languages
local/qt5-multimedia 5.13.0-1 (qt qt5)
    Classes for audio, video, radio and camera functionality
local/qt5-svg 5.13.0-1 (qt qt5)
    Classes for displaying the contents of SVG files
local/qt5-tools 5.13.0-1 (qt qt5)
    A cross-platform application and UI framework (Development Tools, QtHelp)
local/qt5-x11extras 5.13.0-1 (qt qt5)
    Provides platform-specific APIs for X
```
As far as I could see only the first two are used by the Pyside2 modules imported by wwplot. The others are installed because of other programs like vlc and openscad.

**Comment by wwmm** [comment]
The answer to this post  https://stackoverflow.com/questions/56159475/qt-webengine-seems-to-be-initialized suggests it is a bug in Pyside2. But I have my doubts. I do not see this warning. My Pyside2 package version is `5.13.0`

**Comment by yurivict** [comment]
Ok, thanks.
